name: List S3 Buckets
on:
  push:
    branches:
      - main
jobs:
  list_s3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC }}
          aws-region: us-east-1
      - name: List S3 buckets
        run: aws s3 ls

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://my-profile-bucket-code01 \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" 
